package com.zuhlke.scc.web.db.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.NotNull;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "role")
public class Role {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @NotNull
    private String code;


}
