// Mocks generated by Mockito 5.4.2 from annotations
// in scc_poc_app/test/test_utils/nice_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:scc_poc_app/services/scc_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SCCRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSCCRepository extends _i1.Mock implements _i2.SCCRepository {
  @override
  _i3.Future<dynamic> fetchIncidents(String? guardId) => (super.noSuchMethod(
        Invocation.method(
          #fetchIncidents,
          [guardId],
        ),
        returnValue: _i3.Future<dynamic>.value(),
        returnValueForMissingStub: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> fetchIncidentDetail(String? incidentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchIncidentDetail,
          [incidentId],
        ),
        returnValue: _i3.Future<dynamic>.value(),
        returnValueForMissingStub: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> sendToken(
    String? guardId,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendToken,
          [
            guardId,
            token,
          ],
        ),
        returnValue: _i3.Future<dynamic>.value(),
        returnValueForMissingStub: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> sendNote(
    String? incidentId,
    String? description,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendNote,
          [
            incidentId,
            description,
          ],
        ),
        returnValue: _i3.Future<dynamic>.value(),
        returnValueForMissingStub: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> uploadFile(
    String? url,
    _i4.File? file,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [
            url,
            file,
          ],
        ),
        returnValue: _i3.Future<dynamic>.value(),
        returnValueForMissingStub: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
}
