package com.serverless.dal;

import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperConfig;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBScanExpression;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.serverless.exception.EntityNotFoundException;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.IOException;
import java.util.List;

@DynamoDBTable(tableName = "java-incident")
public class Incident {

    // get the table name from env. var. set in serverless.yml
    private static final String TABLE_NAME = System.getenv("PREMISE_TABLE_NAME");

    private static DynamoDBAdapter db_adapter;
    private final AmazonDynamoDB client;
    private final DynamoDBMapper mapper;

    private Logger logger = LogManager.getLogger(this.getClass());

    private String id;
    private String name;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return this.id;
    }
    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBRangeKey(attributeName = "name")
    public String getName() {
        return this.name;
    }
    public void setName(String name) {
        this.name = name;
    }

    public Incident() {
        // build the mapper config
        DynamoDBMapperConfig mapperConfig = DynamoDBMapperConfig.builder()
            .withTableNameOverride(new DynamoDBMapperConfig.TableNameOverride(TABLE_NAME))
            .build();
        // get the db adapter
        Incident.db_adapter = DynamoDBAdapter.getInstance();
        this.client = Incident.db_adapter.getDbClient();
        // create the mapper with config
        this.mapper = Incident.db_adapter.createDbMapper(mapperConfig);
    }

    public String toString() {
        return String.format("Incident [id=%s, name=%s]", this.id, this.name);
    }

    // methods
    public Boolean ifTableExists() {
        return this.client.describeTable(TABLE_NAME).getTable().getTableStatus().equals("ACTIVE");
    }

    public List<Incident> list() throws IOException {
        DynamoDBScanExpression scanExp = new DynamoDBScanExpression();
        List<Incident> results = this.mapper.scan(Incident.class, scanExp);
        for (Incident p : results) {
            logger.info("Incidents - list(): " + p.toString());
        }
        return results;
    }

    public Incident getIncidentById(String id) throws EntityNotFoundException {
        Incident incident = mapper.load(Incident.class, id);

        if (incident == null) {
            throw new EntityNotFoundException("Incident with id " + id + " not found.");
        }

        return incident;
    }
}
